<a href="https://colab.research.google.com/github/jobsiggang/2022/blob/main/%EB%84%98%ED%8C%8C%EC%9D%B4%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**따라하며 배우는 파이썬과 데이터과학(생능출판사 2020)**
강력한 넘파이 배열의 연산을 알아보자

In [ ]:
import numpy as np 
salary = np.array([220, 250, 230])

salary = salary + 100 
print(salary)

[320 350 330]


In [ ]:
import numpy as np 

In [ ]:
array_a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('실습 1 : array_a =', array_a)

실습 1 : array_a = [0 1 2 3 4 5 6 7 8 9]


In [ ]:
array_b = np.array(range(10))
print('실습 2 : array_b =', array_b)

실습 2 : array_b = [0 1 2 3 4 5 6 7 8 9]


In [ ]:
array_c = np.array(range(0,10,2))
print('실습 3 : array_c =', array_c)

실습 3 : array_c = [0 2 4 6 8]


In [ ]:
print('array_c의 shape :', array_c.shape)
print('array_c의 ndim :', array_c.ndim)
print('array_c의 dtype :', array_c.dtype)
print('array_c의 size :', array_c.size)
print('array_c의 itemsize :',array_c.itemsize)

array_c의 shape : (5,)
array_c의 ndim : 1
array_c의 dtype : int64
array_c의 size : 5
array_c의 itemsize : 8


여러 사람의 BMI를 빠르고 간편하게 계산하기

In [ ]:
import numpy as np 
 
heights = [ 1.83, 1.76, 1.69, 1.86, 1.77, 1.73 ] 
weights = [ 86, 74, 59, 95, 80, 68 ] 
 
np_heights = np.array(heights) 
np_weights = np.array(weights) 
 
bmi = np_weights/(np_heights**2) 
print('대상자들의 키:', np_heights)
print('대상자들의 몸무게:', np_weights)
print('대상자들의 BMI')
print(bmi)

대상자들의 키: [1.83 1.76 1.69 1.86 1.77 1.73]
대상자들의 몸무게: [86 74 59 95 80 68]
대상자들의 BMI
[25.68007405 23.88946281 20.65754    27.45982194 25.53544639 22.72043837]


넘파이 배열의 형태 알아내고 슬라이싱하여 연산하기

In [ ]:
import numpy as np 
 
x = np.array([[ 1.83, 1.76, 1.69, 1.86, 1.77, 1.73 ], 
              [ 86.0, 74.0, 59.0, 95.0, 80.0, 68.0 ]]) 
y = x[0:2, 1:3] 
z = x[0:2][1:3]

print('x shape :', x.shape)
print('y shape :', y.shape)
print('z shape :', z.shape)
print('z values = :', z)

bmi = x[0] / x[1]**2
print('BMI data')
print(bmi)

2차원 배열에서 특정 조건을 만족하는 행만 추출하기

In [ ]:
import numpy as np 

players = [[170, 76.4], 
           [183, 86.2], 
           [181, 78.5], 
           [176, 80.1]] 

np_players = np.array(players) 

print('몸무게가 80 이상인 선수 정보')
print(np_players[ np_players[:, 1] >= 80.0 ])

print('키가 180 이상인 선수 정보')
print(np_players[ np_players[:, 0] >= 180.0 ])

넘파이 인덱싱

In [ ]:
np_array=np.array([[1,2,3],[4,5,6,],[7,8,9]])

In [ ]:
print(np_array[0,0])

1


In [ ]:
print(np_array[2,-1])

9


In [ ]:
np_array[0,0]=12
print(np_array)

[[12  2  3]
 [ 4  5  6]
 [ 7  8  9]]


넘파이 슬라이싱  

In [ ]:
np_array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
np_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
print(np_array[0:2,2:4]) #1, 3에서 stop

[[3 4]
 [7 8]]


In [ ]:
np_array[1,1:3]

array([6, 7])

* 파이썬 리스트 슬라이싱과 넘파이 스타일슬라이싱 차이

In [ ]:
print(np_array[::2][::2]) #두번 슬라이싱

[[1 2 3 4]]


In [ ]:
print(np_array[::2,::2]) # 행 슬라이싱: 0행, 2행 선택, 열슬라이싱 : 0열 2열 선택

[[ 1  3]
 [ 9 11]]


In [ ]:
print(np_array[1::2,1::2]) 

[[ 6  8]
 [14 16]]


특정 범위의 정수를 가지는 넘파이 배열만들기

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

시작값부터 끝값까지 균일한 간격으로  지정된 개수 만큼 배열생성하는 linespace()함수

배열의 형태를 바꾸는 reshape()함수와 flatten()함수
